version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ".:/app"
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - '8000:8000'
    env_file: './backend/.env'
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/drawit
    volumes:
      - ".:/app"
    depends_on:
      - db

  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=drawit
    ports:
      - '5432:5432'

  router:
    image: nginx
    volumes:
      - "./frontend/dev.nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - '8080:80'
    depends_on:
      - backend
      - web
