version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ".:/app"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/drawit
      - JWT_SECRET="CHANGE ME"
      - ROCKET_ADDRESS="0.0.0.0"
      - RUN_MIGRATIONS=true
    volumes:
      - ".:/app"
    depends_on:
      - db

  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=drawit

  router:
    image: nginx
    volumes:
      - "./frontend/dev.nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - '8080:80'
    depends_on:
      - backend
      - web
